import { auth, db } from "./firebase-config.js";
import {signInWithEmailAndPassword,signOut,onAuthStateChanged,createUserWithEmailAndPassword,updatePassword,EmailAuthProvider,reauthenticateWithCredential,getAuth} from "https://www.gstatic.com/firebasejs/12.0.0/firebase-auth.js";
import {collection,doc,getDoc,setDoc,addDoc,updateDoc,deleteDoc,onSnapshot,serverTimestamp,writeBatch} from "https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js";
import {initializeApp,getApp,deleteApp} from "https://www.gstatic.com/firebasejs/12.0.0/firebase-app.js";
const defaultData={settings:{organization:'Weazel News',monthlyBudget:18000,currency:'$'},accounts:[],operations:[],invoices:[],employees:[]};
let data=structuredClone(defaultData);let loginAttempts=0;let lockUntil=0;let pendingConfirm=null;let currentUser=null;let firebaseUser=null;let unsubscribers=[];
function loadData(){return structuredClone(defaultData)}
function migrate(d){return d}
function save(){}
const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}).format(Number(n)||0)+' '+data.settings.currency;const dateFr=d=>d?new Date(d+'T00:00:00').toLocaleDateString('fr-FR'):'—';const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const nextId=a=>a.length?Math.max(...a.map(x=>x.id))+1:1;const currentMonth=()=>new Date().toISOString().slice(0,7);const monthLabel=m=>new Date(m+'-01T00:00:00').toLocaleDateString('fr-FR',{month:'long',year:'numeric'});
function usernameToEmail(username){const clean=String(username||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9._-]/g,'');if(!clean)throw new Error('Identifiant invalide');return clean+'@weazel.local'}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function askConfirm(title,text,callback){$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmModal').classList.remove('hidden');pendingConfirm=callback}
$('confirmCancel').onclick=()=>{$('confirmModal').classList.add('hidden');pendingConfirm=null};$('confirmOk').onclick=()=>{if(pendingConfirm)pendingConfirm();$('confirmModal').classList.add('hidden');pendingConfirm=null};
const titles={dashboard:'Tableau de bord',operations:'Opérations',factures:'Factures',employes:'Employés',admin:'Administration'};
function go(page){if(page==='admin'&&currentUser?.role==='lecture')return toast('Votre compte est en lecture seule');document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));$('pageTitle').textContent=titles[page];$('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('.jump-admin').forEach(b=>b.onclick=()=>go('admin'));$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');
function sessionUser(){return currentUser}
function applySession(){$('loginScreen').classList.toggle('hidden',!!currentUser);document.body.classList.remove('role-admin','role-comptable','role-lecture');if(!currentUser)return;document.body.classList.add('role-'+currentUser.role);$('currentUserName').textContent=currentUser.displayName;$('currentUserRole').textContent={admin:'Administrateur',comptable:'Comptable',lecture:'Lecture seule'}[currentUser.role]||currentUser.role;$('userAvatar').textContent=initials(currentUser.displayName);render()}
$('toggleLoginPassword').onclick=()=>{$('loginPassword').type=$('loginPassword').type==='password'?'text':'password'};$('accountLoginForm').onsubmit=async e=>{e.preventDefault();const now=Date.now();if(now<lockUntil){$('loginError').textContent=`Accès verrouillé encore ${Math.ceil((lockUntil-now)/1000)} s.`;return}try{await signInWithEmailAndPassword(auth,usernameToEmail($('loginUsername').value),$('loginPassword').value);loginAttempts=0;$('loginError').textContent='';e.target.reset()}catch(err){loginAttempts++;$('loginError').textContent=`Identifiant ou mot de passe incorrect (${loginAttempts}/3).`;if(loginAttempts>=3){lockUntil=Date.now()+30000;loginAttempts=0;$('loginError').textContent='Trop de tentatives. Accès verrouillé 30 secondes.'}}};
$('accountLogout').onclick=async()=>{await signOut(auth);go('dashboard')};$('adminLogout').onclick=$('accountLogout').onclick;
document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.admin-view').forEach(v=>v.classList.toggle('active',v.id===`admin-${b.dataset.adminTab}`))});
function statusClass(s){return 'status-'+s.replaceAll(' ','-')}
function render(){const month=currentMonth();const monthOps=data.operations.filter(o=>o.date.startsWith(month));const allRev=data.operations.filter(o=>o.type==='revenu').reduce((s,o)=>s+Number(o.amount),0);const allExp=data.operations.filter(o=>o.type==='depense').reduce((s,o)=>s+Number(o.amount),0);const mRev=monthOps.filter(o=>o.type==='revenu').reduce((s,o)=>s+Number(o.amount),0);const mExp=monthOps.filter(o=>o.type==='depense').reduce((s,o)=>s+Number(o.amount),0);const open=data.invoices.filter(i=>i.status!=='Payée');const payroll=data.employees.filter(e=>e.status==='Actif').reduce((s,e)=>s+Number(e.salary),0);
$('statSolde').textContent=money(allRev-allExp);$('balanceTrend').textContent=allRev>=allExp?'Trésorerie positive':'Trésorerie négative';$('statRevenus').textContent=money(mRev);$('revenueCount').textContent=`${monthOps.filter(o=>o.type==='revenu').length} opération(s)`;$('statDepenses').textContent=money(mExp);$('expenseCount').textContent=`${monthOps.filter(o=>o.type==='depense').length} opération(s)`;$('statFactures').textContent=money(open.reduce((s,i)=>s+Number(i.amount),0));$('invoiceCount').textContent=`${open.length} facture(s) ouverte(s)`;$('statPayroll').textContent=money(payroll);$('employeeCount').textContent=`${data.employees.filter(e=>e.status==='Actif').length} employé(s) actif(s)`;
const budget=Number(data.settings.monthlyBudget)||0,p=Math.min(100,budget?Math.round(mExp/budget*100):0);$('budgetPercent').textContent=p+'%';$('budgetSpent').textContent=money(mExp);$('budgetTotal').textContent=money(budget);$('budgetRing').style.background=`conic-gradient(var(--orange) ${p}%,#25252c ${p}%)`;
$('recentOperations').innerHTML=listOrEmpty([...data.operations].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(operationItem));$('dueInvoices').innerHTML=listOrEmpty([...open].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,5).map(i=>`<div class="list-item"><div><strong>${esc(i.title)}</strong><small>${esc(i.party)} · ${dateFr(i.dueDate)}</small></div><span class="status-badge ${statusClass(i.status)}">${esc(i.status)}</span></div>`));
populateMonthFilter();renderOperations();renderInvoices();renderEmployees();renderAdmin();renderChart();fillSettings()}
function listOrEmpty(arr){return arr.length?arr.join(''):'<div class="empty">Aucune donnée à afficher</div>'}
function operationItem(o){return `<div class="list-item"><div><strong>${esc(o.label)}</strong><small>${esc(o.category)} · ${dateFr(o.date)}</small></div><span class="${o.type==='revenu'?'amount-positive':'amount-negative'}">${o.type==='revenu'?'+':'−'} ${money(o.amount)}</span></div>`}
function populateMonthFilter(){const sel=$('operationMonth'),val=sel.value;const months=[...new Set(data.operations.map(o=>o.date.slice(0,7)))].sort().reverse();sel.innerHTML='<option value="all">Tous les mois</option>'+months.map(m=>`<option value="${m}">${monthLabel(m)}</option>`).join('');if([...sel.options].some(o=>o.value===val))sel.value=val}
function renderOperations(){const type=$('operationFilter').value,q=$('operationSearch').value.toLowerCase(),m=$('operationMonth').value;const rows=[...data.operations].filter(o=>(type==='all'||o.type===type)&&(m==='all'||o.date.startsWith(m))&&(`${o.label} ${o.category} ${o.payment}`.toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date));$('operationsTable').innerHTML=rows.length?rows.map(o=>`<tr><td>${dateFr(o.date)}</td><td><span class="type-badge type-${o.type}">${o.type==='revenu'?'Revenu':'Dépense'}</span></td><td><strong>${esc(o.label)}</strong></td><td>${esc(o.category)}</td><td>${esc(o.payment)}</td><td class="${o.type==='revenu'?'amount-positive':'amount-negative'}">${o.type==='revenu'?'+':'−'} ${money(o.amount)}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">Aucune opération trouvée</div></td></tr>';$('operationsTotal').textContent=`${rows.length} résultat(s)`}
function renderInvoices(){const q=$('invoiceSearch').value.toLowerCase(),f=$('invoiceFilter').value;const arr=[...data.invoices].filter(i=>(f==='all'||i.status===f)&&(`${i.party} ${i.title} ${i.reference}`.toLowerCase().includes(q))).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));const sums=['Impayée','En attente','Payée'];$('invoiceSummary').innerHTML=sums.map(s=>`<div class="mini-summary"><span>${s}</span><strong>${money(data.invoices.filter(i=>i.status===s).reduce((x,i)=>x+Number(i.amount),0))}</strong></div>`).join('');$('invoiceCards').innerHTML=arr.length?arr.map(i=>`<article class="invoice-card"><div class="invoice-top"><span class="status-badge ${statusClass(i.status)}">${esc(i.status)}</span><small>${esc(i.reference)}</small></div><h3>${esc(i.title)}</h3><p>${esc(i.party)}</p><div class="invoice-amount">${money(i.amount)}</div><div class="invoice-meta"><span>Échéance</span><strong>${dateFr(i.dueDate)}</strong></div></article>`).join(''):'<div class="empty">Aucune facture trouvée</div>'}
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}function renderEmployees(){const q=$('employeeSearch').value.toLowerCase(),f=$('employeeFilter').value;const arr=data.employees.filter(e=>(f==='all'||e.status===f)&&(`${e.name} ${e.role} ${e.department}`.toLowerCase().includes(q)));$('employeeCards').innerHTML=arr.length?arr.map(e=>`<article class="employee-card"><div class="employee-top"><div class="employee-avatar">${esc(initials(e.name))}</div><span class="status-badge ${statusClass(e.status)}">${esc(e.status)}</span></div><h3>${esc(e.name)}</h3><p>${esc(e.role)} · ${esc(e.department)}</p><div class="employee-salary">${money(e.salary)}</div><p>Salaire mensuel</p><div class="employee-meta"><span>Arrivée</span><strong>${dateFr(e.startDate)}</strong></div></article>`).join(''):'<div class="empty">Aucun employé trouvé</div>'}
function renderAdmin(){const row=(title,sub,col,id,extra='')=>`<div class="list-item"><div><strong>${esc(title)}</strong><small>${esc(sub)}</small></div><div class="item-actions">${extra}<button class="small-btn delete" data-delete="${col}" data-id="${id}">Supprimer</button></div></div>`;$('adminOperations').innerHTML=listOrEmpty([...data.operations].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(o=>row(o.label,money(o.amount),'operations',o.id)));$('adminInvoices').innerHTML=listOrEmpty(data.invoices.map(i=>row(i.title,i.status,'invoices',i.id,`<button class="small-btn" data-cycle-invoice="${i.id}">Statut</button>`)));$('adminEmployees').innerHTML=listOrEmpty(data.employees.map(e=>row(e.name,e.status,'employees',e.id,`<button class="small-btn" data-cycle-employee="${e.id}">Statut</button>`)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>askConfirm('Supprimer cette donnée ?',"Cette action est définitive.",async()=>{await deleteDoc(doc(db,b.dataset.delete,b.dataset.id));toast('Élément supprimé')}));document.querySelectorAll('[data-cycle-invoice]').forEach(b=>b.onclick=async()=>{const i=data.invoices.find(x=>x.id===b.dataset.cycleInvoice),s=['Impayée','En attente','Payée'];if(!i)return;await updateDoc(doc(db,'invoices',i.id),{status:s[(s.indexOf(i.status)+1)%s.length],updatedAt:serverTimestamp()});toast('Statut de la facture modifié')});renderAccounts();document.querySelectorAll('[data-cycle-employee]').forEach(b=>b.onclick=async()=>{const e=data.employees.find(x=>x.id===b.dataset.cycleEmployee),s=['Actif','En congé','Suspendu'];if(!e)return;await updateDoc(doc(db,'employees',e.id),{status:s[(s.indexOf(e.status)+1)%s.length],updatedAt:serverTimestamp()});toast('Statut de l’employé modifié')})}
function renderAccounts(){if(!$('accountsList'))return;const roleLabel={admin:'Administrateur',comptable:'Comptable',lecture:'Lecture seule'};$('accountsList').innerHTML=listOrEmpty(data.accounts.map(a=>`<div class="list-item"><div><strong>${esc(a.displayName)}</strong><small>@${esc(a.username)} · ${roleLabel[a.role]||a.role} · ${a.active?'Actif':'Désactivé'}</small></div><div class="item-actions">${a.id!==currentUser?.id?`<button class="small-btn" data-toggle-account="${a.id}">${a.active?'Désactiver':'Activer'}</button><button class="small-btn delete" data-delete-account="${a.id}">Supprimer le profil</button>`:'<span class="account-role">Vous</span>'}</div></div>`));document.querySelectorAll('[data-toggle-account]').forEach(b=>b.onclick=async()=>{const a=data.accounts.find(x=>x.id===b.dataset.toggleAccount);if(!a)return;await updateDoc(doc(db,'users',a.id),{active:!a.active,updatedAt:serverTimestamp()});toast('Compte mis à jour')});document.querySelectorAll('[data-delete-account]').forEach(b=>b.onclick=()=>askConfirm('Supprimer ce profil ?','Le compte Authentication devra aussi être supprimé dans la console Firebase.',async()=>{await deleteDoc(doc(db,'users',b.dataset.deleteAccount));toast('Profil supprimé')}))}
function renderChart(){const c=$('financeChart'),ctx=c.getContext('2d'),rect=c.getBoundingClientRect(),dpr=window.devicePixelRatio||1;c.width=rect.width*dpr;c.height=rect.height*dpr;ctx.scale(dpr,dpr);const w=rect.width,h=rect.height,n=Number($('chartPeriod').value),now=new Date(),months=[];for(let k=n-1;k>=0;k--){const d=new Date(now.getFullYear(),now.getMonth()-k,1);months.push(d.toISOString().slice(0,7))}const rev=months.map(m=>data.operations.filter(o=>o.type==='revenu'&&o.date.startsWith(m)).reduce((s,o)=>s+Number(o.amount),0)),exp=months.map(m=>data.operations.filter(o=>o.type==='depense'&&o.date.startsWith(m)).reduce((s,o)=>s+Number(o.amount),0)),max=Math.max(...rev,...exp,1)*1.15,pad={l:42,r:15,t:15,b:32};ctx.clearRect(0,0,w,h);ctx.strokeStyle='#292930';ctx.fillStyle='#7f7f89';ctx.font='10px sans-serif';for(let i=0;i<=4;i++){const y=pad.t+(h-pad.t-pad.b)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(Math.round(max*(1-i/4)/1000)+'k',5,y+3)}const draw=(vals,color)=>{ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.beginPath();vals.forEach((v,i)=>{const x=pad.l+(w-pad.l-pad.r)*(i/(Math.max(1,n-1))),y=pad.t+(h-pad.t-pad.b)*(1-v/max);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();vals.forEach((v,i)=>{const x=pad.l+(w-pad.l-pad.r)*(i/(Math.max(1,n-1))),y=pad.t+(h-pad.t-pad.b)*(1-v/max);ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,3.5,0,Math.PI*2);ctx.fill()})};draw(exp,'#686874');draw(rev,'#ff7a00');months.forEach((m,i)=>{const x=pad.l+(w-pad.l-pad.r)*(i/(Math.max(1,n-1)));ctx.fillStyle='#7f7f89';ctx.textAlign='center';ctx.fillText(new Date(m+'-01').toLocaleDateString('fr-FR',{month:'short'}),x,h-8)});ctx.textAlign='left'}
function fillSettings(){const f=$('settingsForm');f.organization.value=data.settings.organization;f.monthlyBudget.value=data.settings.monthlyBudget;f.currency.value=data.settings.currency}
$('operationFilter').onchange=renderOperations;$('operationMonth').onchange=renderOperations;$('operationSearch').oninput=renderOperations;$('invoiceFilter').onchange=renderInvoices;$('invoiceSearch').oninput=renderInvoices;$('employeeFilter').onchange=renderEmployees;$('employeeSearch').oninput=renderEmployees;$('chartPeriod').onchange=renderChart;window.addEventListener('resize',()=>clearTimeout(window.rz)||(window.rz=setTimeout(()=>{renderChart();window.rz=null},150)));
$('operationForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await addDoc(collection(db,'operations'),{type:f.get('type'),label:f.get('label').trim(),category:f.get('category').trim(),payment:f.get('payment'),amount:Number(f.get('amount')),date:f.get('date'),note:f.get('note').trim(),createdAt:serverTimestamp(),createdBy:firebaseUser.uid});e.target.reset();e.target.date.value=new Date().toISOString().slice(0,10);toast('Opération enregistrée')};
$('invoiceForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await addDoc(collection(db,'invoices'),{party:f.get('party').trim(),title:f.get('title').trim(),amount:Number(f.get('amount')),dueDate:f.get('dueDate'),status:f.get('status'),reference:f.get('reference').trim()||`WN-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`,createdAt:serverTimestamp(),createdBy:firebaseUser.uid});e.target.reset();toast('Facture créée')};
$('employeeForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await addDoc(collection(db,'employees'),{name:f.get('name').trim(),role:f.get('role').trim(),department:f.get('department'),salary:Number(f.get('salary')),status:f.get('status'),startDate:f.get('startDate'),createdAt:serverTimestamp(),createdBy:firebaseUser.uid});e.target.reset();toast('Employé ajouté')};
$('accountForm').onsubmit=async e=>{e.preventDefault();if(currentUser?.role!=='admin')return toast('Action réservée aux administrateurs');const f=new FormData(e.target),username=f.get('username').trim().toLowerCase(),email=usernameToEmail(username);if(data.accounts.some(a=>a.username.toLowerCase()===username))return toast('Cet identifiant existe déjà');const secondApp=initializeApp(getApp().options,'secondary-'+Date.now()),secondAuth=getAuth(secondApp);try{const cred=await createUserWithEmailAndPassword(secondAuth,email,f.get('password'));await setDoc(doc(db,'users',cred.user.uid),{displayName:f.get('displayName').trim(),username,email,role:f.get('role'),active:true,createdAt:serverTimestamp(),createdBy:firebaseUser.uid});await signOut(secondAuth);e.target.reset();toast('Compte créé')}catch(err){console.error(err);toast(err.code==='auth/email-already-in-use'?'Cet identifiant existe déjà':'Impossible de créer le compte')}finally{await deleteApp(secondApp)}};
$('settingsForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await setDoc(doc(db,'settings','main'),{organization:f.get('organization').trim()||'Weazel News',monthlyBudget:Number(f.get('monthlyBudget')),currency:f.get('currency'),updatedAt:serverTimestamp(),updatedBy:firebaseUser.uid},{merge:true});toast('Paramètres enregistrés')};
$('passwordForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('next')!==f.get('confirm'))return toast('Les mots de passe ne correspondent pas');try{const credential=EmailAuthProvider.credential(firebaseUser.email,f.get('current'));await reauthenticateWithCredential(firebaseUser,credential);await updatePassword(firebaseUser,f.get('next'));e.target.reset();toast('Mot de passe modifié')}catch(err){console.error(err);toast('Mot de passe actuel incorrect ou modification impossible')}};
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`weazel-finance-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Sauvegarde exportée')}$('exportData').onclick=exportData;$('quickExport').onclick=exportData;
$('importData').onchange=e=>{toast('Import désactivé avec Firebase pour éviter les doublons');e.target.value=''};
$('resetData').onclick=()=>askConfirm('Réinitialiser le site ?','Toutes les opérations, factures et employés seront supprimés.',async()=>{const batch=writeBatch(db);data.operations.forEach(x=>batch.delete(doc(db,'operations',x.id)));data.invoices.forEach(x=>batch.delete(doc(db,'invoices',x.id)));data.employees.forEach(x=>batch.delete(doc(db,'employees',x.id)));batch.set(doc(db,'settings','main'),defaultData.settings,{merge:true});await batch.commit();toast('Données réinitialisées')});
const now=new Date();$('currentPeriod').textContent=now.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});document.querySelector('#operationForm [name=date]').value=now.toISOString().slice(0,10);function startListeners(){unsubscribers.forEach(u=>u());unsubscribers=[onSnapshot(doc(db,'settings','main'),s=>{data.settings=s.exists()?{...defaultData.settings,...s.data()}:structuredClone(defaultData.settings);render()}),onSnapshot(collection(db,'operations'),s=>{data.operations=s.docs.map(d=>({id:d.id,...d.data()}));render()}),onSnapshot(collection(db,'invoices'),s=>{data.invoices=s.docs.map(d=>({id:d.id,...d.data()}));render()}),onSnapshot(collection(db,'employees'),s=>{data.employees=s.docs.map(d=>({id:d.id,...d.data()}));render()}),onSnapshot(collection(db,'users'),s=>{data.accounts=s.docs.map(d=>({id:d.id,...d.data()}));renderAccounts()})]}onAuthStateChanged(auth,async user=>{firebaseUser=user;if(!user){currentUser=null;unsubscribers.forEach(u=>u());unsubscribers=[];applySession();return}const profile=await getDoc(doc(db,'users',user.uid));if(!profile.exists()||profile.data().active!==true){$('loginError').textContent='Profil introuvable ou désactivé';await signOut(auth);return}currentUser={id:user.uid,...profile.data()};applySession();startListeners();toast(`Bienvenue ${currentUser.displayName}`)});
